const menu = [
    {
      id: 1,
      title: 'Maple pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `These delicious pancakes are light and moist. The pancake texture soft and spongy, very yummy must try these`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `Canadian cheese, caramelized onions and All-Canadian sauce on a brioche bun. Served with wavy-cut French fries.`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `The first vanilla-flavoured milkshake, King of Milkshakes and is covered with cookies, donuts and biscuits.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Continental breakfast with wheat bread, egg and cheese. it gives you natural flavour with rich ingredients.`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `Sunnyside is a go-to dish for your hunger attack. You can make it more interesting by adding a few tossed veggies to give you a fuller tummy.`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `We sure do love eating Oreos, but have you tried making a milkshake out of Oreos. Do give it a try.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `Ripe avocado halves filled with an egg, baked to perfection and topped with bacon and cheese. A healthy, easy breakfast. `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `The Classic American Burger is a joy of historic proportions. Tasty, flavorful, and rich in cheese. `,
    },
    {
      id: 9,
      title: 'Nutella waffles',
      category: 'breakfast',
      price: 16.99,
      img: './images/image-9.jpg',
      desc: `These fluffy, short-cut waffles are stuffed with a gooey Nutella filling, perfect for a weekend breakfast treat.`,
    },
    {
        id: 10,
        title: 'Steak Oscar',
        category: 'breakfast',
        price: 16.99,
        img: './images/item-10.jpeg',
        desc: `This absolutely decadent steak oscar recipe combines 4 favorite foods; a darn good steak, crab, asparagus and Hollandaise sauce.`,
      },
      {
        id: 11,
        title: 'Fruit punch',
        category: 'breakfast',
        price: 16.99,
        img: './images/image-11.jpg',
        desc: `This perfect fruit punch gives you flavour of sweet and sour taste touches all your taste buds with a egg yolks.`,
      },
      {
        id: 12,
        title: 'Cobb Salad',
        category: 'lunch',
        price: 16.99,
        img: './images/image-12.jpg',
        desc: `The cobb salad is a main-dish American garden salad that’s created with chicken, bacon, eggs, avocado, blue cheese, and drizzled with a tangy red wine vinegar dressing.`,
      },
      {
        id: 13,
        title: 'Steak Sandwich',
        category: 'lunch',
        price: 16.99,
        img: './images/image-13.jpg',
        desc: `A juicy steak sandwich, piled high with tender slices of steak, tomato, lettuce, caramelised onion, garlic aioli and mustard gives this a "gourmet" spin.`,
      },
      {
        id: 14,
        title: 'Mediterranean Platter',
        category: 'lunch',
        price: 16.99,
        img: './images/image-14.jpg',
        desc: `This is the absolute perfect Mediterranean party platter! With hummus, tabbouleh, almonds, lavash bread and so much more!`,
      },
      {
        id: 15,
        title: 'Tuna Salad Stuffed Avocado',
        category: 'breakfast',
        price: 16.99,
        img: './images/image-15.jpg',
        desc: `Tuna stuffed avocados are a delicious low-carb, keto, Whole30 and paleo-friendly lunch recipe. Try it out.`,
      },
      {
        id: 16,
        title: 'Strawberry Hippie',
        category: 'shakes',
        price: 16.99,
        img: './images/image-16.png',
        desc: `This rich and creamy strawberry milkshake is a breeze to make, this refreshing strawberry milkshake is going to be your favorite all summers.`,
      },

      {
        id: 17,
        title: 'Almond Escape',
        category: 'shakes',
        price: 16.99,
        img: './images/image-17.png',
        desc: `Almond escape is very much delicious shake which is sweet and with the taste of almonds combine with milk and ice make it more refreshing and delicious.`,
      },
  ];
  export default menu;